-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.


CREATE TABLE EMPLOYEE_DETAIL (
    emp_no INT   NOT NULL,
    emp_title_id VARCHAR   NOT NULL,
    birth_date VARCHAR   NOT NULL,
    first_name VARCHAR   NOT NULL,
    last_name VARCHAR   NOT NULL,
    sex VARCHAR   NOT NULL,
    hire_date VARCHAR   NOT NULL,
    CONSTRAINT pk_EMPLOYEE_DETAIL PRIMARY KEY (
        emp_no
     )
);

CREATE TABLE SALARY (
    emp_no INT   NOT NULL,
    salary INT   NOT NULL,
    CONSTRAINT pk_SALARY PRIMARY KEY (
        emp_no
     )
);

CREATE TABLE DEPARTMENT (
    dept_no VARCHAR   NOT NULL,
    dept_name VARCHAR   NOT NULL,
    CONSTRAINT pk_DEPARTMENT PRIMARY KEY (
        dept_no
     )
);

CREATE TABLE EMPLOYEE_STRUCTURE (
    emp_no INT   NOT NULL,
    dept_no VARCHAR   NOT NULL,
    CONSTRAINT pk_EMPLOYEE_STRUCTURE PRIMARY KEY (
        emp_no,dept_no
     )
);

CREATE TABLE ORG_STRUCTURE (
    title_id VARCHAR   NOT NULL,
    title VARCHAR   NOT NULL,
    CONSTRAINT pk_ORG_STRUCTURE PRIMARY KEY (
        title_id
     )
);

CREATE TABLE MANAGER_STRUCTURE (
    dept_no VARCHAR   NOT NULL,
    emp_no INT   NOT NULL,
    CONSTRAINT pk_MANAGER_STRUCTURE PRIMARY KEY (
        dept_no,emp_no
     )
);

ALTER TABLE EMPLOYEE_DETAIL ADD CONSTRAINT fk_EMPLOYEE_DETAIL_emp_no FOREIGN KEY(emp_no)
REFERENCES EMPLOYEE_STRUCTURE (emp_no);

ALTER TABLE SALARY ADD CONSTRAINT fk_SALARY_emp_no FOREIGN KEY(emp_no)
REFERENCES EMPLOYEE_DETAIL (emp_no);

ALTER TABLE DEPARTMENT ADD CONSTRAINT fk_DEPARTMENT_dept_no FOREIGN KEY(dept_no)
REFERENCES EMPLOYEE_STRUCTURE (dept_no);

ALTER TABLE ORG_STRUCTURE ADD CONSTRAINT fk_ORG_STRUCTURE_title_id FOREIGN KEY(title_id)
REFERENCES EMPLOYEE_DETAIL (emp_title_id);

ALTER TABLE MANAGER_STRUCTURE ADD CONSTRAINT fk_MANAGER_STRUCTURE_dept_no FOREIGN KEY(dept_no)
REFERENCES DEPARTMENT (dept_no);

ALTER TABLE MANAGER_STRUCTURE ADD CONSTRAINT fk_MANAGER_STRUCTURE_emp_no FOREIGN KEY(emp_no)
REFERENCES EMPLOYEE_DETAIL (emp_no);

